[env:t5-epd47-s3]
platform = espressif32@6.5.0
board = esp32-s3-devkitc-1
framework = arduino
upload_speed = 921600
monitor_speed = 115200

board_build.arduino.memory_type = qio_opi
board_upload.flash_size = 16MB

build_flags =
    -DBOARD_HAS_PSRAM
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DLILYGO_T5_EPD47_S3
    -DCORE_DEBUG_LEVEL=1

board_build.partitions = default_16MB.csv
board_build.filesystem = littlefs

lib_deps =
    https://github.com/Xinyuan-LilyGO/LilyGo-EPD47.git#esp32s3
    lennarthennigs/Button2@^2.3.2
    bblanchon/ArduinoJson@^7.0.0

monitor_filters = esp32_exception_decoder
